# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 04:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteimoveis', '0002_imovel_cidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
