# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteimoveis', '0004_auto_20170122_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='latitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='longitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
